// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIIghElSNYsy2lPpVlH5c5tkPESNBaCo',
    appId: '1:420215362953:web:1a8794c3f0365b2d2e7d58',
    messagingSenderId: '420215362953',
    projectId: 'movie-app-b7651',
    authDomain: 'movie-app-b7651.firebaseapp.com',
    storageBucket: 'movie-app-b7651.firebasestorage.app',
    measurementId: 'G-RKHET9F9Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYHtfiqSDu0h26eyCGLYmumD7E3SrrXfY',
    appId: '1:420215362953:android:4df1f4670644b2b32e7d58',
    messagingSenderId: '420215362953',
    projectId: 'movie-app-b7651',
    storageBucket: 'movie-app-b7651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEXkCCLYzv6zba7cJxLZgqGVUTef70qs',
    appId: '1:420215362953:ios:88249476e61ef2582e7d58',
    messagingSenderId: '420215362953',
    projectId: 'movie-app-b7651',
    storageBucket: 'movie-app-b7651.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEXkCCLYzv6zba7cJxLZgqGVUTef70qs',
    appId: '1:420215362953:ios:88249476e61ef2582e7d58',
    messagingSenderId: '420215362953',
    projectId: 'movie-app-b7651',
    storageBucket: 'movie-app-b7651.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIIghElSNYsy2lPpVlH5c5tkPESNBaCo',
    appId: '1:420215362953:web:05b7aecffdf3959a2e7d58',
    messagingSenderId: '420215362953',
    projectId: 'movie-app-b7651',
    authDomain: 'movie-app-b7651.firebaseapp.com',
    storageBucket: 'movie-app-b7651.firebasestorage.app',
    measurementId: 'G-77MX96LLPN',
  );
}
